name: DLNLP_25W_Group4
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - pip
  - wheel
  - pip:
      - boto3==1.42.19
      - botocore==1.42.19
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.4.2
      - nltk==3.9.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pip==24.3.1
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==44.1.1
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wikiextractor==3.0.6
